name: scrnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core workflow
  - python
  - snakemake
  - mamba

  # Python packages
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn

  # Utilities
  - pyyaml
  - jinja2
  - graphviz

